Pep8ize ii 4
CCI-MOC/GUI-Backend pull request #25
Opened 2017-03-06 16:03 UTC by robbaronbu

2017-03-06 16:50 UTC, kamfonik approved these changes
Looks good.

2017-03-06 17:37 UTC, knikolla requested changes

2017-03-06 17:37 UTC, knikolla commented on atmosphere/settings/__init__.py
> -from atmosphere.settings.local import *
These are not equivalent.

2017-03-06 17:37 UTC, knikolla commented on core/models/application_version.py
> +        if change_log is not None:
This can be rewritten as ``if change_log``. (optional)

2017-03-06 17:37 UTC, knikolla commented on core/models/application_version.py
> +        if change_log is None:
``if not change_log``. (optional)

2017-03-06 18:06 UTC, kamfonik commented on atmosphere/settings/__init__.py
> -from atmosphere.settings.local import *
Oh, good catch.  I think the same would apply to api/__init__.py (file #2 above)?

2017-03-07 14:11 UTC, merged

2017-03-07 15:33 UTC, xuhang57 commented on api/v1/views/identity_membership.py
> +        if not identity.can_share(request.user):
In L28, " user = request.user" So you don't need a `request` here

2017-03-07 15:33 UTC, xuhang57 commented on api/v1/views/identity_membership.py
> +                % (request.user, identity_uuid))
ditto

2017-03-07 15:33 UTC, xuhang57 commented on api/v1/views/identity_membership.py
> +                % (request.user, identity_uuid))
ditto

2017-03-07 15:33 UTC, xuhang57 commented on api/v2/serializers/post/instance.py
> +from Atmosphere import settings
L63 is using `settings` currently.

2017-03-07 15:33 UTC, xuhang57 commented on service/tasks/monitoring.py
> -def update_membership(application, shared_identities):
why we take the whole function out?

2017-03-07 15:34 UTC, xuhang57 commented
Why you merge this?

2017-03-07 15:51 UTC, jeremyfreudberg commented on api/v1/views/identity_membership.py
> +        if not identity.can_share(request.user):
L28 is in a different class

2017-03-07 16:00 UTC, robbaronbu commented on api/v1/views/identity_membership.py
> +        if not identity.can_share(request.user):
Yes, I had the choice between defining an alias to request.user (as is done in L28) or just using request.  I choose the latter as for 2 function calls.  As jeremy points out L28 is in a different scope that is not accessible from here, so yes you do need something here.

2017-03-07 16:09 UTC, xuhang57 reviewed
Ok. so what is the difference between this PR and the `5`?

2017-03-07 16:09 UTC, xuhang57 commented on api/v1/views/identity_membership.py
> +        if not identity.can_share(request.user):
You guys are right. But if you see L28 and L55. so I believe we should do it consistently.