Add tox and django test framework
CCI-MOC/GUI-Backend pull request #30
Opened 2017-03-10 22:00 UTC by xuhang57

Follow what horizon does upstream. Use tox and django test framework together for unit testing in our code-base.

WIP because I need to figure out how to set up `tox.ini` file properly. Thanks.
Lucas

2017-03-14 19:29 UTC, kamfonik approved these changes
This looks good to me.  I haven't set up tox before, but I looked through the docs and what you have here makes sense.

2017-03-14 19:57 UTC, robbaronbu commented on tox.ini
> +  {[unit_tests]commands}
isn't this more commonly done using the following:
    [tox]
        envlist = {py26,py27}-django{15,16}
    [testenv]
        basepython =
            py26: python2.6
            py27: python2.7
        deps =
            pytest
            django15: Django>=1.5,<1.6
            django16: Django>=1.6,<1.7
            py26: unittest2
        commands = py.test

2017-03-14 20:03 UTC, rob-baron requested changes
Is there a reason why you did the pip install [package] as opposed to adding a deps variable with the packages listed?  If there isn't one, this should be changed to a more standard way.

2017-03-15 20:43 UTC, xuhang57 commented
Found them in the `dev_requirements.txt`

2017-03-17 20:47 UTC, robbaronbu commented on tox.ini
> +  pip install -U django>=1.9,<1.10
isn't this specified in the requirements.txt file on line 32?

2017-03-17 20:51 UTC, rob-baron requested changes
Check to see if django isn't already being included via the requirements.txt file - that way we can get rid of the command in the ini file.

2017-03-17 20:55 UTC, xuhang57 commented on tox.ini
> +  pip install -U django>=1.9,<1.10
This is the standard way to do it. Potentially we need to test with different version of Django as the project grows.

2017-03-18 13:42 UTC, rob-baron approved these changes

2017-03-24 16:32 UTC, merged