Moc openstack login
CCI-MOC/GUI-Backend pull request #34
Opened 2017-03-29 18:57 UTC by robbaronbu

I have moved the changes for the open stack login here.  The unit tests work on my system, need to adjust travis ci file.

2017-03-29 20:19 UTC, xuhang57 commented on api/test/views/mock_keystone.py
> +        elif token == 'gAAAAABY2WAKlR6yxvn1mvkPcW0i4fB36y68N0mg2u1CUjPg7OJ-alV2CPPg207_zOTm8s3p3hHJWYVCw5Jh3PBYECkdplVgdzH7UgviSftNM8AJboFNXbypNNaELqgSztpGh5TnBbXI5RlzAc4IIBWd8wPL-RZuOA':
I am bit confused with this part. Here is checking whether the token is equal to a uuid. A uuid cannot be reproduced. so how this check gonna work?

2017-03-29 20:26 UTC, knikolla commented on api/test/views/mock_keystone.py
> +    This is just a simple view to catch any url we are not handling
update docstring to mention the url your are mocking and what it's doing.

2017-03-29 20:39 UTC, xuhang57 commented
Are we doing this:
https://github.com/openstack/django_openstack_auth/blob/master/openstack_auth/tests/tests.py

Or doing some similar thing here for testing?

2017-03-29 20:39 UTC, xuhang57 commented
https://github.com/openstack/django_openstack_auth/blob/master/openstack_auth/tests/data_v3.py 

If you could have a similar file like this

2017-03-29 20:40 UTC, xuhang57 commented on api/test/views/mock_keystone.py
> +    This is just a simple view to catch any url we are not handling
@knikolla  Should we use port 5000 rather than 8082? Or it doesn't really matter?

2017-03-29 20:42 UTC, xuhang57 commented
And why we want to put this into `GUI-Backend` but not into the django_cyverse_auth`?  Or even we have our `django_moc_auth` just like OpenStack has `django_openstack_auth`?

2017-03-29 21:15 UTC, knikolla commented on api/test/views/mock_keystone.py
> +    This is just a simple view to catch any url we are not handling
@xuhang57 doesn't matter.

2017-03-29 21:18 UTC, knikolla commented on api/test/views/mock_keystone.py
> +        elif token == 'gAAAAABY2WAKlR6yxvn1mvkPcW0i4fB36y68N0mg2u1CUjPg7OJ-alV2CPPg207_zOTm8s3p3hHJWYVCw5Jh3PBYECkdplVgdzH7UgviSftNM8AJboFNXbypNNaELqgSztpGh5TnBbXI5RlzAc4IIBWd8wPL-RZuOA':
@xuhang57 This is not a uuid. But anyway, this is the token we are returning from mock keystone, therefore it IS the token that atmosphere will use for all communications.

2017-03-29 21:32 UTC, robbaronbu commented
We could also just use their test suite, sure.  However, this is how I tested the entire atmosphere + django-cyverse-auth backend.

2017-03-30 01:12 UTC, robbaronbu commented
There are 2 sets of files.  I have placed the MocLogin test file in the atmosphere/tests directory as it is testing the the atmosphere web api.  Granted Django-Cyvers-Auth accesses the keystone client, but so does atmosphere.  I planned to use this to test the projects as well, which are accessing keystone auth from celery.  It makes no sense to place this solely in django-cyverse-auth.

I have placed the mock keystone off off api/test for the following reasons:
    1) This is already a rest api.
    2) I didn't want to rely on an external web server, or anything that required more configuration effort.
    3) It can be conditionally included based off of the configuration file.
    4) it is interacting with the keystone client and not strictly django-cyverse-auth.

2017-03-30 13:49 UTC, xuhang57 requested changes

2017-03-30 13:49 UTC, xuhang57 commented on tests/test_MocLogin.py
> +            '     "default_security_rules": [["ICMP", -1, -1], ["UDP", 20, 20], ["TCP", 20, 21], ["TCP", 22, 23],'\
we don't need these default security rules

2017-03-30 16:14 UTC, xuhang57 commented
a plus one after taking out the security group rules that we don't need

2017-04-04 21:38 UTC, xuhang57 commented
resolve conflict and a plus one. feel free to merge after that.

2017-04-05 16:03 UTC, robbaronbu commented on tests/test_MocLogin.py
> +            '     "default_security_rules": [["ICMP", -1, -1], ["UDP", 20, 20], ["TCP", 20, 21], ["TCP", 22, 23],'\
OK, I have clipped them to a subset.  Should have a few so that we accurately represent what the cloud_config contains.

2017-04-06 15:15 UTC, xuhang57 approved these changes

2017-04-06 19:47 UTC, knikolla approved these changes

2017-04-06 19:49 UTC, merged